apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xfunctions.example.upbound.io
spec:
  claimNames:
    kind: Function
    plural: functions
  group: example.upbound.io
  names:
    kind: XFunction
    plural: xfunctions
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: Define Serverless Function Parameter Specifications
              properties:
                parameters:
                  description: Function Parameters
                  properties:
                    deletionPolicy:
                      description: When the Composition is deleleted, delelete the AWS resources. Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    region:
                      description: Cloud region
                      default: us-east-1
                      type: string
                    s3BucketName:
                      description: S3 bucket location containing the function's deployment package. This bucket must reside in the same AWS region where you are creating the Lambda function.
                      type: string
                    s3ObjectKey:
                      description: S3 key of an object containing the function's Zip deployment package
                      type: string
                    s3ObjectVersion:
                      description: Object version containing the function's deployment package.
                      type: string
                    handler:
                      description: Function entrypoint in your code.
                      type: string
                    environmentVariables:
                      description: Map of Environment variables to pass to the function.
                      type: object
                      additionalProperties:
                        type: string
                    tags:
                      description: Map of additional AWS Tags to add to all resources
                      additionalProperties:
                        type: string
                      type: object
                  required:
                  - deletionPolicy
                  - handler
                  - providerConfigName
                  - region
                  - s3BucketName
                  - s3ObjectKey
                  type: object
              required:
              - parameters
              type: object
            status:
              description: Status of the Function
              properties:
                functionArn:
                  type: string
                functionName:
                  type: string
              type: object
          type: object
