apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xparameters.example.upbound.io
spec:
  claimNames:
    kind: Parameter
    plural: parameters
  group: example.upbound.io
  names:
    kind: XParameter
    plural: xparameters
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              description: Define SSM Parameter Specifications
              properties:
                parameters:
                  description: SSM Parameter Parameters
                  properties:
                    deletionPolicy:
                      description: When the Composition is deleleted, delelete the AWS resources. Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    region:
                      description: Cloud region
                      default: us-east-1
                      type: string
                    insecureValue:
                      description: Value of the parameter 
                      type: string
                    parameterName:
                      description: Name of the parameter.  When you reference a parameter that is part of a hierarchy, specify the entire hierarchy path including the initial slash (/).
                      type: string
                    tags:
                      description: Map of additional AWS Tags to add to all resources
                      additionalProperties:
                        type: string
                      type: object
                  required:
                  - deletionPolicy
                  - insecureValue
                  - parameterName
                  - providerConfigName
                  - region
                  type: object
              required:
              - parameters
              type: object
            status:
              description: Status of the Parameter
              properties:
                parameterId:
                  type: string
                parameterArn:
                  type: string
                parameterName:
                  type: string
              type: object
          type: object                                                                                                                            (⎈|kind-kind:N/A)➜  SSMParameters git:(main) ✗ 
